### ISSUE TITLE
Module not found: Can't resolve 'remark-directive-rehype' in 

### ISSUE THREAD

**Issue by geyang** [IGassmann/remark-directive-rehype#10] opened 2022-11-17 04:26 UTC
This is similar to #2 but the exact error message is different.

```
Module not found: Can't resolve 'remark-directive-rehype' in 
```

I am on the newest version

**Comment by geyang** [comment] 2022-11-17 04:45
Solved by importing from `/dist`

**Comment by IGassmann** [comment] 2022-11-17 11:12
@geyang, thanks for filling this issue!

Would you be able to provide instructions for me to reproduce this error?

**Comment by geyang** [comment] 2022-11-17 14:39
Hey Igor, not sure because my setup is a bit complicated. Will try to come
back to this issue but I might be swamped by job search and RSS deadline
till next year

Thanks for this amazing library! Super useful

**Comment by IGassmann** [comment] 2023-04-19 09:38
Closing due to activity.

**Closed by IGassmann** 2023-04-19 09:38 UTC
